version: '2'
services:
  rails_app:
    build: .
    ports:
     - "3000:3000"
    volumes:
     - .:/app
     - ./container_scripts:/container_scripts
    depends_on:
     - db
    links:
     - db
  db:
    image: postgres
    ports:
     - "5432:5432"